# Generated by Django 5.0.6 on 2024-07-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('uses_nbr', models.PositiveIntegerField(default=1)),
                ('expiration_date', models.DateField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=255)),
                ('dte_acquisition', models.DateField()),
                ('ram', models.CharField(max_length=255)),
                ('disque_dur', models.CharField(max_length=255)),
                ('processeur', models.CharField(max_length=255)),
                ('ecran', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('statut', models.CharField(max_length=255)),
                ('intitule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('poste', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('motifs', models.CharField(max_length=250)),
                ('ordinateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinateur.ordinateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinateur.personne')),
            ],
        ),
    ]
