# Generated by Django 5.0.6 on 2024-07-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='departement',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='marque',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='nombre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='numero_seri',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='ordi',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='telephone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='utilisateur',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panne',
            name='statut',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
