# Generated by Django 5.0.6 on 2024-07-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinateur', '0002_panne_departement_panne_marque_panne_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='ordi',
        ),
    ]
