# Generated by Django 5.0.6 on 2024-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinateur', '0003_remove_panne_ordi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('intitule', models.TextField()),
                ('utilisateur', models.TextField()),
                ('telephone', models.IntegerField()),
                ('marque', models.TextField()),
                ('departement', models.TextField()),
            ],
        ),
    ]
