# Generated by Django 5.0.6 on 2024-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinateur', '0004_histo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
