# Generated by Django 5.0.6 on 2024-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinateur', '0005_alter_histo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='panne',
            name='numero_seri',
            field=models.IntegerField(null=True),
        ),
    ]
