# Generated by Django 5.0.6 on 2024-10-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinateur', '0006_alter_panne_date_alter_panne_numero_seri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='nombre',
        ),
    ]
