# Generated by Django 5.0.6 on 2024-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinateur', '0007_remove_panne_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='nombre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
